# Generated by Django 4.1.7 on 2023-04-12 07:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userApp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
