# Generated by Django 3.2.18 on 2023-04-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='title',
        ),
        migrations.AddField(
            model_name='diary',
            name='user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
