# Generated by Django 4.1.7 on 2023-04-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recordApp", "0002_auto_20230406_2148"),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("path", models.CharField(max_length=100)),
                ("path2", models.CharField(max_length=100)),
                ("create_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "photo",
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("path", models.CharField(max_length=100)),
                ("path2", models.CharField(max_length=100)),
                ("pic", models.CharField(max_length=100)),
                ("create_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "video",
            },
        ),
        migrations.RemoveField(
            model_name="diary",
            name="updated_at",
        ),
    ]
