# Generated by Django 3.2 on 2023-05-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordApp', '0003_photo_video_remove_diary_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grow_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=100)),
                ('path2', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('height', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'grow_record',
            },
        ),
    ]
