# Generated by Django 3.2 on 2023-05-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordApp', '0004_grow_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=500)),
                ('robot', models.CharField(max_length=500)),
                ('query_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chat_record',
            },
        ),
    ]
